services:
  lftp-gui:
    build: .
    container_name: lftp-gui
    restart: unless-stopped
    ports:
      - "9342:9342"
    volumes:
      # Persistent configuration, logs, and transfer history
      - /mnt/user/appstorage/lftp-gui:/config
      # Local Upload Folder containing files to upload/push
      - /mnt/user/appstorage/lftp-gui/upload:/local-push
      # Local Download Folder where files will be downloaded/pulled
      - /mnt/user/appstorage/lftp-gui/download:/local-pull
      # SSH key authentication files
      - /mnt/user/appstorage/authentication/docker:/root/.ssh
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
